/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.dearrudam.multiproject.impl;

import io.github.dearrudam.multiproject.spec.MyService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
public class MyServiceImpl implements MyService {

    private final String message;

    public MyServiceImpl(@Value(value = "${message}") String message) {
        this.message = message;
    }

    @Override
    public String doSomething() {
        return this.message;
    }
}
