/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.dearrudam.multiproject;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class MyApplicationTest {
    @Test
    void contextLoads() {
    }
}
